### ISSUE TITLE
RuntimeError: Failed to import diffusers.loaders.unet because of the following error: cannot import name 'EncoderDecoderCache' from 'transformers' (C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\transformers\__init__.py)

### ISSUE THREAD

**Issue by rtx3060laptop** [ant-research/MagicQuill#79]
When I run the command, I end up with the following error. I tried updating transformers library and the diffusers library, recreating the Environment but I still get the error. Please help me fix it. Thanks.

(MagicQuill) G:\MagicQuill>python gradio_run.py
Total VRAM 6144 MB, total RAM 16201 MB
pytorch version: 2.1.2+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : native
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\diffusers\utils\import_utils.py", line 853, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\diffusers\loaders\unet.py", line 46, in <module>
    from .lora_pipeline import LORA_WEIGHT_NAME, LORA_WEIGHT_NAME_SAFE, TEXT_ENCODER_NAME, UNET_NAME
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\diffusers\loaders\lora_pipeline.py", line 36, in <module>
    from .lora_base import LoraBaseMixin
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\diffusers\loaders\lora_base.py", line 47, in <module>
    from peft.tuners.tuners_utils import BaseTunerLayer
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\peft\auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\peft\mapping.py", line 25, in <module>
    from .mixed_model import PeftMixedModel
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\peft\mixed_model.py", line 29, in <module>
    from .peft_model import PeftModel
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\peft\peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\transformers\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "G:\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "G:\MagicQuill\MagicQuill\brushnet_nodes.py", line 21, in <module>
    from .brushnet.brushnet import BrushNetModel
  File "G:\MagicQuill\MagicQuill\brushnet\brushnet.py", line 20, in <module>
    from .unet_2d_blocks import (
  File "G:\MagicQuill\MagicQuill\brushnet\unet_2d_blocks.py", line 36, in <module>
    from diffusers.models.transformers.dual_transformer_2d import DualTransformer2DModel
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\diffusers\models\transformers\__init__.py", line 13, in <module>
    from .prior_transformer import PriorTransformer
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\diffusers\models\transformers\prior_transformer.py", line 9, in <module>
    from ...loaders import PeftAdapterMixin, UNet2DConditionLoadersMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (C:\Users\seth\.conda\envs\MagicQuill\lib\site-packages\transformers\__init__.py)

**Comment by Basurer** [comment]
I have the same error on a 4090.

RuntimeError: Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (C:\Users\hal9000\.conda\envs\MagicQuill\lib\site-packages\transformers\__init__.py)

**Comment by Dazmo1221** [comment]
RuntimeError: Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (C:\Users\seth.conda\envs\MagicQuill\lib\site-packages\transformers_init.py)

**Comment by puwalski** [comment]
RuntimeError: Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (C:\Users\tomas\miniconda3\envs\MagicQuill\lib\site-packages\transformers\__init__.py)
Error: Failed to run MagicQuill.

**Comment by bflamand** [comment]
yep, can confirm that the build is broken... Chatgpt seams to think this is because the diffusers and transformers versions are not compatible. Tried to upgrade manually the diffuser version, but I still have issues after that: Magicquill loads the models but eventually it just returns to my anaconda prompt without any errors...

**Comment by FurkanGozukara** [comment]
i have python 3.10 venv windows installers published if you cant figure out - paywalled

i also have installers for runpod and massed compute - works with cloudflared share link https://www.patreon.com/posts/magicquill-1-for-117326651

![image](https://github.com/user-attachments/assets/1c633b9a-accb-4b54-b869-df196654d1b1)

**Comment by craigsimm** [comment]
I get the same error on a 4070.

**Comment by zliucz** [comment]
We’ll look into this issue asap.

**Comment by adi32k** [comment]
For me this fixed the issue:

pip install --upgrade transformers diffusers peft

In file "MagicQuill/LLaVA/llava/model/builder.py"  comment line 35: "kwargs['load_in_4bit'] = True"
Puth # in front of it

**Comment by zliucz** [comment]
@bflamand @puwalski @rtx3060laptop @Basurer @Dazmo1221 @bflamand @craigsimm 

Hi, there. Try this:

```
pip install peft==0.13.2
```

 I think this issue is because the environment mismatch with the latest `peft` package. I will update the requirement soon.

**Comment by puwalski** [comment]
After applying the suggested fix, everything started working, but another error appears when I try to perform any operation:
`The size of tensor a (640) must match the size of tensor b (320) at non-singleton dimension 1`
I saw that this problem was reported in another thread, unfortunately without a solution so far.

**Comment by zliucz** [comment]
@puwalski Unfortunately, we haven't encountered this specific issue in our testing environments, so I cannot provide a definitive solution at this point 😭. We'll continue investigating this bug and let you know if we found any solutions.

**Comment by craigsimm** [comment]
> @bflamand @puwalski @rtx3060laptop @Basurer @Dazmo1221 @craigsimm
> 
> Hi, there. Try this:
> 
> ```
> pip install peft==0.13.2
> ```
> 
> I think this issue is because some conflict with the latest `peft` package. I will update the requirement soon.

This fixed the issue for me, thank you!

**Comment by Dazmo1221** [comment]
RuntimeError: The size of tensor a (640) must match the size of tensor b (320) at non-singleton dimension 1
INFO:     127.0.0.1:50037 - "POST /gradio_api/queue/join HTTP/1.1" 200 OK
INFO:     127.0.0.1:50037 - "GET /gradio_api/queue/data?session_hash=a7gy9bg9yw HTTP/1.1" 200 OK
Apply edge controlnet
Base model type: SD1.5
BrushNet image.shape = torch.Size([1, 665, 512, 3]) mask.shape = torch.Size([1, 665, 512])
Requested to load AutoencoderKL
Loading 1 new model
loading in lowvram mode 64.0
BrushNet CL: image_latents shape = torch.Size([1, 4, 83, 64]) interpolated_mask shape = torch.Size([1, 1, 83, 64])
Requested to load ControlNet
Requested to load BaseModel
Loading 2 new models
loading in lowvram mode 64.0
loading in lowvram mode 64.0
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]BrushNet inference, step = 0: image batch = 1, got 1 latents, starting from 0
BrushNet inference: sample torch.Size([1, 4, 83, 64]) , CL torch.Size([1, 5, 83, 64]) dtype torch.float16
BrushNet can't find <class 'comfy.ops.disable_weight_init.Conv2d'> layer in 0 input block: None
  0%|                                                                                           | 0/20 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\gradio\blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\gradio\blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "C:\MagicQuill\gradio_run.py", line 155, in generate_image_handler
    res = generate(
  File "C:\MagicQuill\gradio_run.py", line 123, in generate
    latent_samples, final_image, lineart_output, color_output = scribbleColorEditModel.process(
  File "C:\MagicQuill\MagicQuill\scribble_color_edit.py", line 110, in process
    latent_samples = self.ksampler.sample(
  File "C:\MagicQuill\MagicQuill\comfyui_utils.py", line 154, in sample
    return self.common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\MagicQuill\MagicQuill\comfyui_utils.py", line 146, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\MagicQuill\MagicQuill\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\MagicQuill\MagicQuill\comfy\samplers.py", line 794, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\MagicQuill\MagicQuill\model_patch.py", line 120, in modified_sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "C:\MagicQuill\MagicQuill\comfy\samplers.py", line 683, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "C:\MagicQuill\MagicQuill\comfy\samplers.py", line 662, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\MagicQuill\MagicQuill\comfy\samplers.py", line 567, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\MagicQuill\MagicQuill\comfy\k_diffusion\sampling.py", line 159, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\MagicQuill\MagicQuill\comfy\samplers.py", line 291, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "C:\MagicQuill\MagicQuill\comfy\samplers.py", line 649, in __call__
    return self.predict_noise(*args, **kwargs)
  File "C:\MagicQuill\MagicQuill\comfy\samplers.py", line 652, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "C:\MagicQuill\MagicQuill\comfy\samplers.py", line 277, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "C:\MagicQuill\MagicQuill\comfy\samplers.py", line 224, in calc_cond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "C:\MagicQuill\MagicQuill\model_patch.py", line 52, in brushnet_model_function_wrapper
    return apply_model_method(x, timestep, **options_dict['c'])
  File "C:\MagicQuill\MagicQuill\comfy\model_base.py", line 113, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MagicQuill\MagicQuill\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 852, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "C:\MagicQuill\MagicQuill\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 44, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\gamit\anaconda3\envs\MagicQuill\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MagicQuill\MagicQuill\brushnet_nodes.py", line 1070, in forward_patched_by_brushnet
    h += to_add.to(h.dtype).to(h.device)
RuntimeError: The size of tensor a (640) must match the size of tensor b (320) at non-singleton dimension 1

help
