### ISSUE TITLE
OSError: Incorrect path_or_model_id: 'F:\TOOL\MagicQuill\models\llava-v1.5-7b-finetune-clean'

### ISSUE THREAD

**Issue by Firman2024-ffs** [ant-research/MagicQuill#93]
i have an error like this, how to solve this?

(MagicQuill) F:\TOOL\MagicQuill>python gradio_run.py
Total VRAM 4096 MB, total RAM 16234 MB
pytorch version: 2.1.2+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1050 Ti : native
Using pytorch cross attention
['F:\\TOOL\\MagicQuill', 'C:\\Users\\Fanny Firman Syah\\.conda\\envs\\MagicQuill\\python310.zip', 'C:\\Users\\Fanny Firman Syah\\.conda\\envs\\MagicQuill\\DLLs', 'C:\\Users\\Fanny Firman Syah\\.conda\\envs\\MagicQuill\\lib', 'C:\\Users\\Fanny Firman Syah\\.conda\\envs\\MagicQuill', 'C:\\Users\\Fanny Firman Syah\\.conda\\envs\\MagicQuill\\lib\\site-packages', '__editable__.llava-1.2.2.post1.finder.__path_hook__', 'F:\\TOOL\\MagicQuill\\MagicQuill']
Traceback (most recent call last):
  File "C:\Users\Fanny Firman Syah\.conda\envs\MagicQuill\lib\site-packages\transformers\utils\hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\Fanny Firman Syah\.conda\envs\MagicQuill\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\Fanny Firman Syah\.conda\envs\MagicQuill\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'F:\TOOL\MagicQuill\models\llava-v1.5-7b-finetune-clean'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\TOOL\MagicQuill\gradio_run.py", line 24, in <module>
    llavaModel = LLaVAModel()
  File "F:\TOOL\MagicQuill\MagicQuill\llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "F:\TOOL\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 116, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "C:\Users\Fanny Firman Syah\.conda\envs\MagicQuill\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 758, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Fanny Firman Syah\.conda\envs\MagicQuill\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 590, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "C:\Users\Fanny Firman Syah\.conda\envs\MagicQuill\lib\site-packages\transformers\utils\hub.py", line 450, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'F:\TOOL\MagicQuill\models\llava-v1.5-7b-finetune-clean'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by zliucz** [comment]
Hi, check this [issue#54](https://github.com/magic-quill/MagicQuill/issues/54). Take a screenshot at your folder at path `F:\TOOL\MagicQuill\models\llava-v1.5-7b-finetune-clean` would help us find the problem.

**Comment by nimish-shah** [comment]
I'm having a similar issue.  The directory where I cloned the repository to was D:\git\MagicQuill.  That is the directory where windows_setup.bat is located.  I did clone using the --recursive flag.

When I try to run the installation, it gives me a similar error with just the path names being slightly different.

    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\git\MagicQuill\models\llava-v1.5-7b-finetune-clean'.

I don't have a models directory under D:\git\MagicQuill.
